# Wasmer.io Configuration
[package]
name = "php-tacview-analysis"
version = "1.0.0"
description = "PHP Tacview Analysis Tool for DCS World"

[dependencies]

[fs]
"/public" = "."

[commands]
start = "php -S 0.0.0.0:8000 -t /public"